### ISSUE TITLE
Bullseye KDE Plasma NO Sound

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#1000]
Hi @ophub and KDE Plasma users,

Downloaded Armbian_23.02.0_amlogic_s922x-reva_bullseye_6.1.9_server_2023.0 and installed the latest KDE Plasma from Debian Unstable repo using:

sudo apt -t unstable install tasksel
sudo apt -t unstable install task-kde-desktop

Successfully installed KDE Plasma on Bullseye but NO Sound is available.  SystemSettings "Audio" shows blank like there is NO soundcard.  The "Sound Volume" icon at the bottom panel indicates NO Sound available.

![image](https://user-images.githubusercontent.com/75384411/216395584-9defb9cc-0d56-46ea-a7ae-7fe98e1df245.png)

aplay -l and cat /proc/asound/cards indicates soundcard is available.

```
jfl@armbian:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: GTKINGPRO [GTKINGPRO], device 0: fe.dai-link-0 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: GTKINGPRO [GTKINGPRO], device 1: fe.dai-link-1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: GTKINGPRO [GTKINGPRO], device 2: fe.dai-link-2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

jfl@armbian:~$ cat /proc/asound/cards
 0 [GTKINGPRO      ]: axg-sound-card - GTKINGPRO
                      GTKINGPRO
```
Appreciate some guidances or tips how to enable Sound on Debian Bullseye KDE Plasma.

On your image on Bullseye-Gnome or Jammy-Gnome sound is available out of the box.

Edit: If sound is available the KDE Plasma "systemsettings" Audio should look something like this:
![image](https://user-images.githubusercontent.com/75384411/216501475-18e3d9dc-b1aa-4cce-9ce0-f38cfcf7b0b8.png)

But somehow NO Playback Devices is listed on  Armbian_23.02.0_amlogic_s922x-reva_bullseye_6.1.9_KDE-Plasma so NO sound output.

**Comment by langyxxl** [comment]
https://github.com/Scirese/alarm/issues/2 
try this, maybe same problem

**Comment by JFLim1** [comment]
Hi @langyxxl & @ophub

I do know about g12_sound.sh and sound.sh where I used it on Manjaro-Arm and on the old Armbin-5.9.0 image to get sound on my device.

I thought Ophub's aml-s922X images already have the sound preset and not using g12_sound.sh to set or configure the sound card. 

On the earlier Ophub's aml-s922X Jammy image, I installed Gnome DE and sound is available right after installation and reboot.  The option of event Multi-Channel sound option is available!

With the latest Armbian_23.02.0_amlogic_s922x-reva_bullseye_6.1.9_server I face numerous issue on first boot up.  WIFI was not detected or inconsistend detection even during first boot up after flashing..

Reflash Armbian_23.02.0_amlogic_s922x-reva_bullseye_6.1.9_server on USB drive and still having the WIFI detection issue. During first boot up WIFI was NOT detected as such NOT set/configured.

Plugin Ethernet and this help in WIFI detection after boot up (no idea why).  Use "armbian-config" to set up the WIFI.  Install KDE Plasma again and still NO Sound.

```
[ 1977.024064]  fe.dai-link-1: ASoC: no backend DAIs enabled for fe.dai-link-1
[ 1977.030735]  fe.dai-link-1: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-1: -22
[ 1977.039198]  fe.dai-link-1: ASoC: no backend DAIs enabled for fe.dai-link-1
```

@ophub Is there a sound configuration file that I need to edit (like g12_sound.sh) to enable sound through HDMI or "Built-In Audio"?

**Comment by JFLim1** [comment]
Hi @langyxxl and @ophub 

The g12_sound.sh did the trick on Bullsleye-KDE Plasma but only "Stereo Output".  

@ophub am bit confused in the sense, why on Jammy Gnome sound is available **without** having to run "g12_sound.sh" and also "Multi-Channel" Output is available.

Without resolving the "Sound" issue, pulseaudio daemon hog or load one CPU core to around 100%.  Once run "g12_sound.sh" the CPU load reduces immediately.

**Comment by ophub** [comment]
@7Ji

https://github.com/Scirese/alarm/issues/2#issuecomment-1327103213

你在这个问题里的解决办法，JFLim1 测试有效。如果把这个压缩包解压了直接添加到 Jammy和Bullsleye 默认固件里，对 Jammy 有没什么副作用？
Jammy 为什么可以工作而 Bullsleye 需要添加？你给帮忙解答下这个问题。

**Comment by 7Ji** [comment]
> 如果把这个压缩包解压了直接添加到所有的 Jammy和Bullsleye 默认固件里，对 Jammy 有没什么副作用？

> On your image on Bullseye-Gnome or Jammy-Gnome sound is available out of the box.

> The g12_sound.sh did the trick on Bullsleye-KDE Plasma but only "Stereo Output"

> Without resolving the "Sound" issue, pulseaudio daemon hog or load one CPU core to around 100%.

This should not be added as a default config file as:
1. It is not a problem with Bullseye, but Bullseye + Plasma, since Bullseye + Gnome works fine, adding it could probaly conflict with the existing working Gnome config.
2. The script has a LOT of sutffs going on under the hood, and it expects an environment where none of the sound config was made. It is for the case of Arch, where audio daemons are just there without config after installing them, but certainly not for Armbian, where the distro already packs a lot of pre-configured stuffs before the user even use them.
3. It does not fix  the problem completely. There ARE already some auto-config sutffs going on and that's why the pulseaudio daemon went 100%, it is probably getting a LOT of config requests from the auto-config stuffs before the sound started to work, then that auto-config stuff stopped the full profile to work (hence, only stereo). 

> Jammy 为什么可以工作而 Bullsleye 需要添加？

Probably yet another different decision between the packagers of Ubuntu and Debian for the same package (I've seen a lot), especially on the config. If a distro decides your config, it's then not surprising that a derived distro choose something different from the parent distro. And Ubuntu loves to push more things (ah my painful experience uninstalling their pre-installed cloud-init on servers again and again)

I need to do some tests on a spare box to get exactly what different configs are there, but that'll not come soon.

**Comment by ophub** [comment]
Ok, thanks for sharing your experience.

**Comment by JFLim1** [comment]
> Probably yet another different decision between the packagers of Ubuntu and Debian for the same package (I've seen a lot), especially on the config. If a distro decides your config, it's then not surprising that a derived distro choose something different from the parent distro. And Ubuntu loves to push more things (ah my painful experience uninstalling their pre-installed cloud-init on servers again and again)

In my experience in general, it is easier to install Desktop Environment on Ubuntu Jammy/Kinetic  and get the expected out of the box working than installing Desktop Environment on Debian Bullseye/Sid especially KDE Plasma.

**Comment by JFLim1** [comment]
Hi @ophub & @7Ji 

Just an update on aml-s922x-Bullseye-KDE sound.  Earlier I had alluded that after running "g12_sound.sh" only "Stereo Output" is available.  But today, i check KDE "systemsettings --> Audio" and I noticed Multi-Channel sound is also available just like in Jammy-Gnome image.

![image](https://user-images.githubusercontent.com/75384411/217470844-83835bcf-c0d3-48c7-939a-a724ba067793.png)

All is good. No idea what changes lead to this though.
