### ISSUE TITLE
Would you please enable CONFIG_CMDLINE_PARTITION option in kernel 6.1?

### ISSUE THREAD

**Issue by zechfox** [ophub/amlogic-s9xxx-armbian#1073]
Hi,
I have learn the issue[https://github.com/ophub/amlogic-s9xxx-armbian/issues/457](url) and try to install armbian to emmc on S905 device.
And I noticed that you have enabled the CONFIG_CMDLINE_PARTITION in kernel 5.10 and 5.4, but leave 5.15 and 6.1 alone.
Would you please also enable CONFIG_CMDLINE_PARTITION for kernel 5.15 and 6.1?
Thanks in advanced~

**Comment by ophub** [comment]
Compiled by myself, added in config.

My kernel repository was packaged by someone else who dumped it, and he didn't enable it.

**Comment by zechfox** [comment]
Thanks for your reply. I will try to follow your instructions to compile it.

**Comment by 7Ji** [comment]
Releases in my [amlogic-s9xxx-archlinuxarm](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm) project has the option enabled since [half a month ago](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm/commit/bd5ce7e119f5453f9e74fb9ff7887f16cf993850) as a result of me tinkering with mibox3 (mdz-16-aa, s905)

You could try to extract the built AUR packages from release artifact `ArchLinuxARM-aarch64-Amlogic-*-pkgs.tar.xz` from the latest release on the [release page](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm/releases), and then extract the kernel, dtbs and headers from the pacakges `linux-aarch64-flippy-*-aarch64.pkg.tar`, `linux-aarch64-flippy-dtb-amlogic-*-aarch64.pkg.tar` and `linux-aarch64-flippy-headers-*-aarch64.pkg.tar` and place them in your Armbian installation (names are much different so be sure you make them right)

And I would recommend against placing everything inside one partition. Instead, it's better to define sperate partitions for kernel, initramfs and dtb, and use udev rules to create symlinks under `/dev/block` to point to them, and include thoese important existing partition you identify with [ampart](https://github.com/7Ji/ampart) (should already come pre-installed in your Armbian installation) in your `blkdevparts` definition, so you won't accidentally overwrite existing important data.  Said udev rules, scripts and some essential steps can be found in my [blog post](https://7ji.github.io/embedded/2023/02/20/gxbb-emmc.html)

**Comment by zechfox** [comment]
@7Ji Thanks for your reply. I had fork @ophub 's repo compile the kernel with CONFIG_CMDLINE_PARTITION succefully.
And I have see the /dev/mmcblk2p2 partition, but still failed when I try to install armbian to emmc. I use the ampart tools, and find out that my device didn't have same 'env' partition as  https://github.com/d51x/armbian-s905/blob/main/emmc_install/v2/README.MD. I modity the script, but still failed. BTW: your ampart tool is brilliant!
But then I made a stupid thing: I try to using armbian-install script to port armbian to emmc instead of d51x's script. I think the armbian-install script overwrites my boodloader partition of my emmc, my device can't boot up again, even with usb stick. Then I try to use usb_burning_tool to flash it, but can't find the device. 
I can't catch the TTL log because I didn't solder it. 
I also suspect that the chip is broken, because usb_burning_tool should flash it even though bootloader was corrupt.
I will try to solder the TTL to catch the log to make sure S905 is good, then flash the emmc offline if possible. 
Do you have any suggestion about how to fix the brick? Thanks~

**Comment by 7Ji** [comment]
> I try to using armbian-install script

This is why it was bricked. The whole reason why you must use cmdline-partition is that Amlogic made a big mistake to define the area where MBR and GPT should be stored should be used to store their bootloader. And since armbian-install will create MBR partition tables, you just corrupted the bootloader.

Just install things manually to partitions and don't rely on installation guider/scripts. You can decide every detail in your installation this way.

**Comment by 7Ji** [comment]
Also if you're using 6.1 kernel, you can try 6.1.14 since it has my patch to support Amlogic's partitions built-in. You just need to add either `apt_blkdevs=mmcblk2` or `apt_blkdevs=all` to let the kernel parse such partitions, so you can avoid the hassles in calculating command line partitions' offset and size by hand. The support is added in the block subsystem and it's the last in priority so don't use `blkdevparts` in this case.

A trivial is that since ampart was designed when there's no mainline kernel support for such partitions, you'll need to call `blockdev --rereadpt -v /dev/mmcblk2` to let the kernel re-parse the partitions after you run ampart to modify them.

**Comment by zechfox** [comment]
I regret I didn't read your reply before running armbian install script.
I will manually install Linux according to your guide. Before I create new partitions, I have to fix the brick. Do you have any suggestions about how to fix the brick? I can't boot it with usb stick or flash it by usb_burning_tool.

**Comment by 7Ji** [comment]
Take the box apart and check if you can find either: 1) a pair of test copper spots, or 2 ) eMMC chip with visible tin pins

By shorting either the spots, or 5th and 6th pins on one side of the eMMC chip, you can force the eMMC chip into access mode, which makes it not readable by the SoC so SoC will then be forced to bunring mode.

**Comment by zechfox** [comment]
I had short two spot near emmc as website described. But the S905 was not detected by usb_burning_tool. I'm not sure the chip was broken or I short wrong spot. Anyway, I will try get TTL log to make sure the chip is good. Thanks again for your great help!
