### ISSUE TITLE
Not space avaible in /var/log

### ISSUE THREAD

**Issue by uroh** [ophub/amlogic-s9xxx-armbian#1106]
Standard chat template, no routine, no chat.

**Device Information
 - SOC: [S095x3]
 - Model [max plus]

**Armbian Version 
 - Kernel Version: [last 5.15.xx]
 - Release: [bullseye]

**Describe the bug
Hello,
I have encountered a small issue in the /var/log folder where I am running out of available space within a few days. The problem appears to be caused by the SYSSTAT service which generates numerous files from the server's start-up (I have deleted the files and restarted), quickly occupying 82% of the available space.
This problem was not present with the previous kernel version (5.15.85). Has anyone else experienced the same issue?

![Schermata 2023-02-25 alle 07 57 10](https://user-images.githubusercontent.com/46243951/221343606-27307e3f-78cc-4bba-b807-d136807e06af.png)

![Schermata 2023-02-25 alle 08 02 13](https://user-images.githubusercontent.com/46243951/221343728-a3110014-a718-45e7-87da-63d96894a19e.png)

![Schermata 2023-02-25 alle 08 04 23](https://user-images.githubusercontent.com/46243951/221343823-30074d18-f4e8-4c75-88de-308d52d7bfbc.png)

**Comment by SoraKasvgano** [comment]
turn off zram log function

https://www.jianshu.com/p/02ea2504516a

/usr/lib/armbian/armbian-ramlog
```
syncToDisk () {
    isSafe
 
    echo -e "\n\n$(date): Syncing logs from $LOG_TYPE to storage\n" | $LOG_OUTPUT
```
add 
```
syncToDisk () {
    # no sync to protect emmc
    return 0
    isSafe
```

**Comment by SoraKasvgano** [comment]
or direct it to /dev/null?

**Comment by 7Ji** [comment]
Turning off zram log will just mitigate the problem but not solve the root cause. There is something generating a lot of log and without `/var/log` being a seperate mount point the one being filled up will then be the root fs itself.

My gut feeling is that some kernel modules is not behaving, being too verbose on their kmesg log. And since you're using 5.15 it could be some Android-oriented wireless modules ported to that kernel that generates a lot of logs there.

Could you paste the `dmesg` result?

**Comment by uroh** [comment]
here is the output of the dmesg. After 1 day it grew from 82% to 85%. Ugh!
[log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10843372/log.txt)

**Comment by xsetiadi** [comment]
try to expand the partition size.

edit this file: armbian-ramlog on /etc/default

increase the size from 50M to 500M or more. up to you
