### ISSUE TITLE
hk1 death after 1 day online with light load

### ISSUE THREAD

**Issue by BobDLA** [ophub/amlogic-s9xxx-armbian#1167]
Install HK1 with 5.15 kernal latest version.
And it's online and only with light loading since last evening.
It did not online anymore this morning. From the router side, no online info.And can't ssh to the hk1 box also.
After repower the board, checked the /var/log/ folder. But,no clues from the dmesg, syslog etc logs.
Is there any common method to find the root cause?
Any suggestion?

Thanks

**Comment by 7Ji** [comment]
By default Armbian mounts a zram fs to `/var/log` which is different from standard Linux distros, to minimize writes to flash-based storage. 

The travia is that is will try to rotate logs to non-volatile storage but that's only done hourly, certainly leading to loss of logs if you're not shutting down cleanly (on purpose to have to)

If you want to keep the whole feature but just turn that off for debugging, edit `/etc/default/armbian-ramlog` and set `ENABLED` key to anything but `true` and reboot. The logs will then be written directly to your persistent storage.

But even if you are writing logs to non-volatile storage, you could still be unlucky to not get enough log to backtrack the problem: the kernel could be broken to the stage where writing log is impossible. So you should not rely on this.

Reliable way to get the kernel log is always from the UART console, which needs a soldered UART socket onboard, a less ideal way is to keep a monitor always plugged to HDMI and powered on (don't power off it, as said the kernel could be broken to the stage where re-enable the display is out-of-the-way). The latter is less ideal because if the system hardlocks you will be unable to scroll the console.

**Comment by BobDLA** [comment]
> By default Armbian mounts a zram fs to `/var/log` which is different from standard Linux distros, to minimize writes to flash-based storage.
> 
> The travia is that is will try to rotate logs to non-volatile storage but that's only done hourly, certainly leading to loss of logs if you're not shutting down cleanly (on purpose or have to)
> 
> If you want to keep the whole feature but just turn that off for debugging, edit `/etc/default/armbian-ramlog` and set `ENABLED` key to anything but `true` and reboot. The logs will then be written directly to your persistent storage.
> 
> But even if you are writing logs to non-volatile storage, you could still be unlucky to not get enough log to backtrack the problem: the kernel could be broken to the stage where writing log is impossible. So you should not rely on this.
> 
> Reliable way to get the kernel log is always from the UART console, which needs a soldered UART socket onboard, a less ideal way is to keep a monitor always plugged to HDMI and powered on (don't power off it, as said the kernel could be broken to the stage where re-enable the display is out-of-the-way). The latter is less ideal because if the system hardlocks you will be unable to scroll the console.

Thank you for your guidance. The /var/log/log.hdd folder was confused me before ;-). 
The HK1 box has a USB serial port， connect to computer by the Type-a to Type-a  port. It's worked when flash image. 
Maybe it could be used for monitor also.
I will try and feedback later.

**Comment by 7Ji** [comment]
> The HK1 box has a USB serial port， connect to computer by the Type-a to Type-a port. It's worked when flash image.
Maybe it could be used for monitor also.

No, if you want to use the USB 2.0 type-A port for serial debugging you will need to tinker with the kernel USB gadget subsystem and do some DT modification or userspace sysfs write to force the USB controller glue layer to put that port into peripheral mode, as type-A port does not have otg-id pin and auto-negotiation will fail so that port is locked to host mode on HK1 Box. 

 (For Amlogic's pre-boot flashing/debug capability, that's because it forced the otg port on SoC to work in peripheral mode)

You will need a dtbo compiled from [this dts in my repo](https://github.com/7Ji/device-trees/blob/master/overlay/meson-force-usb-peripheral.dts) to make kernel force the port to work as a peripheral port, and then load module `g_serial` to virtulize the box as a CDC-ACM device to your PC on the other end, and I don't think Windows has driver for CDC-ACM.

And then the CDC-ACM serial port will probably not work as a console as I don't think the current kernel in this repo has essential modules built. Even built you will need to patch the initramfs to make it work at early userspace.

All of these, if you don't have enough knowledge, is asking for trouble as you will fail at here and there.

---

The easiest way, is to open the box, and solder a 4-pin UART socket onto the board, then use USB-serial converter to connect to it.

**Comment by BobDLA** [comment]
From the dmesg , I always get this kind of log

Modules linked in: xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nft_counter xt_addrtype nft_compat nf_tables nfnetlink br_netfilter bridge cpufreq_userspace cpufreq_conservative cpufreq_powersave sunrpc btsdio zram brcmfmac brcmutil hci_uart btqca btrtl btintel btbcm cfg80211 bluetooth panfrost snd_soc_meson_axg_sound_card snd_soc_meson_card_utils gpu_sched rfkill snd_soc_meson_g12a_tohdmitx snd_soc_meson_codec_glue snd_soc_meson_axg_tdmout meson_vdec(C) snd_soc_meson_axg_frddr meson_gxbb_wdt videobuf2_dma_contig v4l2_mem2mem ir_nec_decoder snd_soc_meson_axg_fifo meson_ir snd_soc_meson_axg_tdm_interface snd_soc_meson_axg_tdm_formatter tcp_bbr sch_fq ip_tables x_tables
[Sat Mar 18 19:47:10 2023] CPU: 3 PID: 0 Comm: swapper/3 Tainted: G         C        5.15.98-flippy-82+o #214
[Sat Mar 18 19:47:10 2023] Hardware name: HK1 Box/Vontar X3 (DT)
[Sat Mar 18 19:47:10 2023] pstate: 604000c9 (nZCv daIF +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[Sat Mar 18 19:47:10 2023] pc : rcu_eqs_exit+0x74/0x7c
[Sat Mar 18 19:47:10 2023] lr : rcu_eqs_exit+0x44/0x7c
[Sat Mar 18 19:47:10 2023] sp : ffffffc0080b3d80
[Sat Mar 18 19:47:10 2023] x29: ffffffc0080b3d80 x28: 0000000000000000 x27: 0000000000000000
[Sat Mar 18 19:47:10 2023] x26: 0000000000000000 x25: 0000000000000000 x24: 0000000000000000
[Sat Mar 18 19:47:10 2023] x23: ffffffc00a62e9f0 x22: ffffffc00a62e000 x21: ffffff80000b7000
[Sat Mar 18 19:47:10 2023] x20: 0000000000000000 x19: ffffff80dd773dc0 x18: 0000000000000000
[Sat Mar 18 19:47:10 2023] x17: 00000000000003af x16: ffffffc00a1c885c x15: 0000000000000005
[Sat Mar 18 19:47:10 2023] x14: 0000000000000005 x13: 0000000000000005 x12: ffffffc00a1b0eb8
[Sat Mar 18 19:47:10 2023] x11: 0000000000000000 x10: 00000000003af807 x9 : 0000000000000001
[Sat Mar 18 19:47:10 2023] x8 : 0010000000000000 x7 : 0000000000000000 x6 : 0000000000000000
[Sat Mar 18 19:47:10 2023] x5 : ffffffc008bcbda4 x4 : 0000000000000000 x3 : ffffffc008bcbc60
[Sat Mar 18 19:47:10 2023] x2 : 0000000000000001 x1 : ffffffc00a17e59e x0 : 00000000003af807
[Sat Mar 18 19:47:10 2023] Call trace:
[Sat Mar 18 19:47:10 2023]  rcu_eqs_exit+0x74/0x7c
[Sat Mar 18 19:47:10 2023]  rcu_idle_exit+0x2c/0x6c
[Sat Mar 18 19:47:10 2023]  default_idle_call+0x34/0x84
[Sat Mar 18 19:47:10 2023]  cpuidle_idle_call+0x68/0x1bc
[Sat Mar 18 19:47:10 2023]  do_idle.llvm.16740906602074487240+0x88/0xcc
[Sat Mar 18 19:47:10 2023]  cpu_startup_entry+0x24/0x28
[Sat Mar 18 19:47:10 2023]  secondary_start_kernel+0x19c/0x240
[Sat Mar 18 19:47:10 2023]  __secondary_switched+0x94/0x98
[Sat Mar 18 19:47:10 2023] ---[ end trace d280c72d86512bb6 ]---



Is that critial error log?
Should I put the error to some other repo?


Thanks
