### ISSUE TITLE
Hdmi completely turns off after logging in ubuntu desktop

### ISSUE THREAD

**Issue by marohinmark** [ophub/amlogic-s9xxx-armbian#125]
Hello, I installed ubuntu-desktop on armbian focal 5.15.2 s905x3 on h96 max x3, and when I log in ubuntu desktop on X11,  hdmi completely turns off! How can I fix this (panfrost seems to be working without installing additional software, no lag in gdm3)

**Comment by marohinmark** [comment]
Wayland launches just fine! Also, any tips on how to rebuild kernel with custom kernel config ?

**Comment by marohinmark** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel
> 
> Modify the configuration to enable what you need：
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config

but how to fix not able to type in gnome terminal and not able to login in ubuntu (not gnome) desktop session on both wayland and x11?

**Comment by ophub** [comment]
`armbian-config`
You can try to install the desktop through the built-in method. I don't have a monitor, I don't have a desktop installed, and I usually use ssh to access it.

**Comment by marohinmark** [comment]
> yes, I mainly use docker, openwrt, webdav, audio and video entertainment, compile programs.
> 
> I put him in a cabinet and use it as a server. ssh network access.
> 
> I only connect the box to the TV at home on occasional debugging to see the output code during boot.
> 
> I only have a laptop. I didn't think about whether to buy a monitor or not, I rarely need to use it.

also, what is the default config for compiling armbian in  your repo?

**Comment by marohinmark** [comment]
config-5.15.24?

**Comment by JFLim1** [comment]
> when I log in ubuntu desktop on X11, hdmi completely turns off!

I had similar experience on GT King Pro Ubuntu-Focal with kernel 5.15.15 when logon to Ubuntu Session (Xorg/X11) -- Black Screen/No hdmi output but it works well (actually very smooth with GPU Acceleration - Panfrost) on Ubuntu on Wayland Session.  As far as I can tell in my case it wasn't due to the "hdmi-hotplug" issue.  As I have basically removed the "hdmi-hotplug" file.

On Khadas-Vim3-Gnome-Focal-mainline kernel also the same issue Ubuntu (Xorg/X11) session just black screen and Ubuntu on Wayland works.

At times, the keyboard does not work or responsive but after unplug and replug keyboard it works again but this might not be same in your case as the mouse and keyboard is inserted into a USB 3.0 4-Port Hub.

Could it be a dtb issue on your case?

**Comment by marohinmark** [comment]
> On some versions of Armbian there is a script /usr/local/bin/hdmi-hotplug which is run regularly by some systemd service (I think) to check that the monitor is connected. A quick hack to fix the screen turning black is then to edit the relevant line in the script to read HDMI_CONNECTOR=connected
> 
> (I don't know if this applies to the Armbian version in question here, since I'm only using the kernel flippy-70+ (thx for the good work, by the way!).)
> 
> Edit: spelling

HDMI_STATUS*, but thx

**Comment by JFLim1** [comment]
My experience is on Armbian-Focal-Gnome or Khadas-Vim3-Gnome (firmware from Khadas) is that somehow Ubuntu-Xorg will just show a blank screen if you try to log on even if the "hdmi-hotplug" is modify to include "HDMI_CONNECTOR=connected" or totally remove "hdmi-hotplug" file.

On these two firmware I can only logon to Ubuntu-Wayland session.  

For your info, on Ubuntu Impish or Armbian Jammy (by @ophub) I can logon to Ubuntu Xorg or Ubuntu (Wayland).
