### ISSUE TITLE
How to boot into Armbian on Xiaomi Mibox3 (MDZ-16-AA)?

### ISSUE THREAD

**Issue by phantuanphong** [ophub/amlogic-s9xxx-armbian#1359]
I want mibox boot into Armbian distro, how to do that? Thanks you! @7Ji

**Comment by 7Ji** [comment]
It's not possible to sideload any system from external storage on a MDZ-16-AA with the stock Android image, so you have to replace either the bootloader or the whole system on eMMC:
 1. Open up the box and you should see the backside of the PCB
 2. At the bottom of the PCB, near the front IR receiver, you should see two copper test pins close to each other
 3. Keep the box powered off, and keep the two pins shorted with a metal tool
 4. Plug a USB-A to USB-A cable to the box, which another end connected to a Windows PC
 5. You should hear a new device notify sound if it goes successfully, and the HDMI output should be black instead of booting into system so you can connect a monitor to verify. If not, unplug everything and go back to step 3
 6. You should release the tool you use to short the pins now
 7. Use Amlogic USB Burning Tool to flash `mibox3-bare-but-mainline.img` at https://github.com/7Ji/u-boot/releases/tag/v2023.01-mibox3 onto the box. **This will erase everything on your eMMC**
 8. If flash is successful, you can now load any distro, this Armbian included, with mainline Linux kernel, from the USB port. It's recommended to boot via `/extlinux/extlinux.conf` though, as it's now the prefered way for mainline u-boot.
 9. If you can boot into a system on USB, you can then install to eMMC followed the method I wrote at https://7ji.github.io/embedded/2023/02/20/gxbb-emmc.html

**Comment by phantuanphong** [comment]
Thanks you so much!

**Comment by rehiy** [comment]
教程来啦，不需要短接  https://www.rehiy.com/post/609/?6
