### ISSUE TITLE
历史版本在那里

### ISSUE THREAD

**Issue by gametta** [ophub/amlogic-s9xxx-armbian#1389]
最近使用新版本遇到一些问题，以前用老版本没有这个问题，因为总是喜欢更新，造成老版本找不到的问题，
麻烦O大能够提供一下历史版本下载的地方，

**Comment by ophub** [comment]
没有历史版本，周更周删。

**Comment by gametta** [comment]
这个习惯不好啊，最起码保持半年再删除，如果没有空间我可以保存啊

**Comment by gametta** [comment]
O大的工作量很大，我看到了，我也希望能够尽一份力，我可以提供一个ftp，目前剩余空间30T左右，动态域名，300M上，如果许可的话，可以再分发到其他网盘分流。

**Comment by ophub** [comment]
好啊，非常感谢你的支持。

https://mirrors.tuna.tsinghua.edu.cn/armbian-releases/
你会做这种镜像站的存储吗？或者类似这种的，能提供目录浏览和文件下载的。
放 Armbian 和 kernel 

https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_05.09.2000
https://github.com/ophub/kernel/releases/tag/kernel_stable

镜像有2种: Jammy 和 Bullseye
内核有4中: stable, flippy, rk3588, dev

**Comment by ophub** [comment]
可以。文件支持wget下载即可。

**Comment by JFLim1** [comment]
> There are 4 kernels: stable, flippy, rk3588, dev

Hi @ophub,

For normal daily use on Beelink GT King Pro should I use kernel-stable or kernel-flippy?  What is the difference between kernel-stable and kernel-flippy?  For example I notice there are kernel-6.1.27-ophub and kernel-6.1.27-flippy-83+ available.

**Comment by Scirese** [comment]
其实我们可以减少一下生成镜像的数量, 目前我们要为每个 SoC 都生成一份镜像, 而这些镜像的差别仅仅就只是启动配置和 motd. 显然没必要仅仅为了这一点差别就重新生成一份镜像, 把能统一的都统一起来, 每次 release 只需要发4份镜像 - Amlogic, Allwinner, Rockchip 和 Rock5B, 都按 800M 计算, 总大小还不到 3.5G. 
如何修改启动配置在文档里有讲, 这个步骤交给用户是完全可以的. 镜像还可以使用 xz 来最大程度的压缩, 算下来这个使用量完全可以在 Github 上保留几个版本.

稍久远的历史版本可以发到 Onedrive 上, Onedrive 很轻松就能拿到 5T 免费空间, 再搭配 Alist 这些, 也完全能做到镜像站的效果.

**Comment by ophub** [comment]
> For normal daily use on Beelink GT King Pro should I use kernel-stable or kernel-flippy? What is the difference between kernel-stable and kernel-flippy? For example I notice there are kernel-6.1.27-ophub and kernel-6.1.27-flippy-83+ available.

The [kernel_flippy](https://github.com/ophub/kernel/releases/tag/kernel_flippy), [kernel_stable](https://github.com/ophub/kernel/releases/tag/kernel_stable), and [kernel_dev](https://github.com/ophub/kernel/releases/tag/kernel_dev) are universal kernels that can be interchanged. Flippy's feature is being more user-friendly, Stable is more intimate, and Dev is smoother.

**Comment by ophub** [comment]
https://github.com/armbian/community/releases/tag/23.05.0-trunk-e33842ef2

我看了下armbian的releases里，一个tags下保存了3千多个文件。我想我是不是也狠心一点多保存一些吧。
暂定以后的tags按月创建，每个月的历史镜像都增量保存不删档了。

**Comment by JFLim1** [comment]
> The [kernel_flippy](https://github.com/ophub/kernel/releases/tag/kernel_flippy), [kernel_stable](https://github.com/ophub/kernel/releases/tag/kernel_stable), and [kernel_dev](https://github.com/ophub/kernel/releases/tag/kernel_dev) are universal kernels that can be interchanged. Flippy's feature is being more user-friendly, Stable is more intimate, and Dev is smoother.

Hi @ophub,

Thanks for the response.  Based on the kernel size taking kernel-6.1.28 as example, flippy-72.1MB, Stable-85.8MB and Dev-90.1MB, is it safe to assume that Stable has additional patches over Flippy and Dev has additional patches over Stable?

**Comment by ophub** [comment]
Small differences between the 3 kernel series:

`Flippy`: This is the standard, original version. It is characterized by being more user-friendly.

`Stable`: `More support options` have been gradually enabled based on user requests in the Flippy config template over the years. It is characterized by being more thoughtful.

`Dev`: The config used is the same as stable, but when compiling the kernel source locally, several `patches` provided by users were added. For example, the `TEXT_OFFSET` patch was added to the 5.10/6.1 series, allowing this series of kernels to be used on devices without a dedicated uboot. It is characterized by being smoother.

Using an iPhone analogy: Flippy is iPhone X, Stable is iPhone X Pro, and Dev is iPhone X Max. However, `the incremental changes in Stable and Dev are not universally necessary`. Since the Stable and Dev series are incremental changes, they can theoretically be interchanged with the Flippy series. However, because I don't understand the kernel, I'm not sure if these increments have negative effects. Therefore, `it is recommended to use the Flippy series on main devices` and switch around with other experimental devices using the Stable and Dev series.
