### ISSUE TITLE
Cannot install rtl8821CU driver

### ISSUE THREAD

**Issue by wildy2828** [ophub/amlogic-s9xxx-armbian#1607]
hello, I got an error when installing the rtl8821CU driver, the error description from dmks is that the files in /lib/modules/kernel/scripts/mods cannot be exec because of different architectures 

is there a solution to install the driver? 

I'm using Armbian_bookworm_save_2023.08

**Comment by ophub** [comment]
Different architectures cannot be used.
Find the mainline kernel driver, arm64

**Comment by wildy2828** [comment]
https://github.com/brektrou/rtl8821CU 
i used that source driver from git and installed using dkms

**Comment by wildy2828** [comment]
![Screenshot from 2023-08-12 17-18-04](https://github.com/ophub/amlogic-s9xxx-armbian/assets/135487348/bfbdfac0-30b5-4385-b52c-593297d485cf)

**Comment by ophub** [comment]
first: `armbian-update -u dev -k 5.15.126`

then, try again

**Comment by wildy2828** [comment]
Thank you, 

the issue has been solved by re-cross-compiling the module within the kernel.

**Comment by bench2012** [comment]
Hi,

I ran into the same issue, how did you solve it? I am using kernel 6.1.42 and trying to compile driver for rtl88x2bu wifi.

Many thanks,

bench2046

**Comment by wildy658** [comment]
> 

i using kerne 6.1 and got the same issue [ couldn't compile ]

i downgraded to 5.15.x and it worked

**Comment by bench2012** [comment]
Hi,

I found a way, but it is a bit of a hack. What I found has fail during the compilation of the driver is that these two scripts in the header files were compile in x86 instead of arch64: depfix and postmod. I guess these don't change much from between version, so I copy them from another version (older I think, 6.1.11) to mine, which is 6.1.47  and it works. Of course, YMMV.  

Don't know if anyone should fix these script in the header or not.


Anyway, hope this helps.
