### ISSUE TITLE
好像无法运行Arm32 位的程序，请问内核编译的时候是否有配置支持 Arm32位程序

### ISSUE THREAD

**Issue by aaftio** [ophub/amlogic-s9xxx-armbian#1614]
**Device Information | 设备信息**
 - SOC: [S905l3b]
 - Model [ty1608]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.121]
 - Release: [jammy]

**Describe the bug | 问题描述**
在运行网心云的时候有arm32位程序，无法正常启动，是否是因为内核编译的时候没有启动32位支持？
https://stackoverflow.com/questions/34648832/can-old-arm32-binary-files-be-run-on-aarch64-kernel
查看上面的问答的时候有提到内核是这样配置，不清楚当前内核编译是怎么配置的

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config

内核配置文件

**Comment by 7Ji** [comment]
```
menuconfig COMPAT
        bool "Kernel support for 32-bit EL0"
        depends on ARM64_4K_PAGES || EXPERT
        select HAVE_UID16
        select OLD_SIGSUSPEND3
        select COMPAT_OLD_SIGACTION
        help
          This option enables support for a 32-bit EL0 running under a 64-bit
          kernel at EL1. AArch32-specific components such as system calls,
          the user helper functions, VFP support and the ptrace interface are
          handled appropriately by the kernel.

          If you use a page size other than 4KB (i.e, 16KB or 64KB), please be aware
          that you will only be able to execute AArch32 binaries that were compiled
          with page size aligned segments.

          If you want to execute 32-bit userspace applications, say Y.
```
HAVE_UID16, OLD_SIGSUSPEND3, COMPAT_OLD_SIGACTION all enabled in the current kernel configs (and I doubt there will be anyone compiling an AArch64 kernel disabling them) so kernel is not the problem here.

You need a complete 32-bit userspace to run 32-bit programs, at least a 32-bit linker (ld) and a 32-bit glibc. Adding armelhf as an alternative architecture to your APT config then installing armelhf's glibc should be enough.

**Comment by aaftio** [comment]
我测试了自己编译的32位程序可以运行，而且也通过 [此方法添加了32位动态链库](https://forum.armbian.com/topic/4764-running-32-bit-applications-on-aarch64/)，还是无法正常运行网心，可能是和网心自己的程序有关。
