### ISSUE TITLE
Support for Allwinner H616 and H313. DietPi.

### ISSUE THREAD

**Issue by siliconhippy** [ophub/amlogic-s9xxx-armbian#1636]
Hi !

Great development and documentation! Armbian doesn't support tv box development and after balbes150 removed S905xx support, Armbian.com wasn't very useful. 

DietPi is very useful for x86_64 but they too don't support tv boxes !

1. I prompted Bing Skype chatGPT and it said you support Allwinner H616. But I cannot find links, except for H6.
Please provide a link 🙏.

2. Is H3 supported too, or is it just basically H6?

3. Any plans to support Amlogic S905w2 ?

4. Is there any comparison chart with DietPi or you basically support all DietPi features for tv boxes ?

Cheers 🤡
shippy.

**Comment by ophub** [comment]
ChatGPT might not be describing the current situation; it's possible that it is accurately predicting future scenarios. I also believe that supporting this aspect in the future is a possibility.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/CONTRIBUTORS.md

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf


From the list of contributors, it can be observed that all the devices are developed and tested by enthusiastic contributors. I merely serve as a recorder to include the usage reports provided by the contributors in the list of devices.

Due to my limited capabilities and lack of devices, I am unable to add support for more unknown devices. If there are relevant reports available, I will document them.

**Comment by siliconhippy** [comment]
Ok thanks, great work 😸
Yes I am familiar with balbes150 work from years ago, and chatted with him on Armbian then.
