### ISSUE TITLE
is support rknpu?

### ISSUE THREAD

**Issue by shirakun** [ophub/amlogic-s9xxx-armbian#2030]
Hi
I have some rk devices such as photonicat (rk3568) and panther x2 (rk3566).
When I tried to use rknpu in armbian yesterday, I realized that armbian doesn't have a driver for rknpu.
Is there any way to make rk npu work under armbian?

**Comment by HelloTheAsia** [comment]
最近我在折腾x2使用jellyfin驱动vpu硬件解码.希望能够为您提供些思路.
我在折腾的过程中发现它的dts中的关于vpu与npu的选项都是disabled.
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/2f59f84f-a892-41da-9db1-afd39dba949e)
所以在现在的系统中.肯定也是无法驱动的.
我继续尝试将disabled简单的改为okay,也是不行的.
但是我后续发现使用同为3566的JP-BOX dts,x2居然可以启动.并且vpu是正常识别和驱动的.硬件解码也是可以顺利进行.我看到JP-BOX的npu也是开启的.你可以去尝试是否能运行,你想要运行的项目.
因为dts并不完全匹配.导致有些外设无法使用 目前发现tf卡无法使用.

The following content is from Google Translate:
Recently, I have been tossing around with x2 using jellyfin to drive vpu hardware decoding. I hope it can provide you with some ideas.
During the process of tossing around, I found that the options for vpu and npu in its dts are all disabled.
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/2f59f84f-a892-41da-9db1-afd39dba949e)
So in the current system, it definitely cannot be driven.
I continued to try to simply change disabled to okay, but that didn't work either.
But I later found that using the same JP-BOX dts of 3566, x2 can actually be started. And the vpu is recognized and driven normally. Hardware decoding can also be carried out smoothly. I saw that the npu of JP-BOX is also turned on. You can go Try to see if it can run the project you want to run.
Because the dts do not completely match, some peripherals cannot be used. Currently, it is found that the tf card cannot be used.

**Comment by shirakun** [comment]
> 最近我在折腾x2使用jellyfin驱动vpu硬件解码.希望能够为您提供些思路. 我在折腾的过程中发现它的dts中的关于vpu与npu的选项都是disabled. ![image](https://private-user-images.githubusercontent.com/26612794/297241682-2f59f84f-a892-41da-9db1-afd39dba949e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjE4MjksIm5iZiI6MTcwNTQ2MTUyOSwicGF0aCI6Ii8yNjYxMjc5NC8yOTcyNDE2ODItMmY1OWY4NGYtYTg5Mi00MWRhLTlkYjEtYWZkMzlkYmE5NDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZDA2ZWRlZmFmNWNiNmE4YmJjODYzMjc3MDBhOGM3ZTkxMjgxOThkNWVmMWUyY2JmMWRlNDUwNWY5Yzc5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gLXPKPfX1DOxFtt3GFfJUo-Gz3vG7FSHT1kUd5aGLIk) 所以在现在的系统中.肯定也是无法驱动的. 我继续尝试将disabled简单的改为okay,也是不行的. 但是我后续发现使用同为3566的JP-BOX dts,x2居然可以启动.并且vpu是正常识别和驱动的.硬件解码也是可以顺利进行.我看到JP-BOX的npu也是开启的.你可以去尝试是否能运行,你想要运行的项目. 因为dts并不完全匹配.导致有些外设无法使用 目前发现tf卡无法使用.
> 
> The following content is from Google Translate: Recently, I have been tossing around with x2 using jellyfin to drive vpu hardware decoding. I hope it can provide you with some ideas. During the process of tossing around, I found that the options for vpu and npu in its dts are all disabled. ![image](https://private-user-images.githubusercontent.com/26612794/297241682-2f59f84f-a892-41da-9db1-afd39dba949e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjE4MjksIm5iZiI6MTcwNTQ2MTUyOSwicGF0aCI6Ii8yNjYxMjc5NC8yOTcyNDE2ODItMmY1OWY4NGYtYTg5Mi00MWRhLTlkYjEtYWZkMzlkYmE5NDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZDA2ZWRlZmFmNWNiNmE4YmJjODYzMjc3MDBhOGM3ZTkxMjgxOThkNWVmMWUyY2JmMWRlNDUwNWY5Yzc5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gLXPKPfX1DOxFtt3GFfJUo-Gz3vG7FSHT1kUd5aGLIk) So in the current system, it definitely cannot be driven. I continued to try to simply change disabled to okay, but that didn't work either. But I later found that using the same JP-BOX dts of 3566, x2 can actually be started. And the vpu is recognized and driven normally. Hardware decoding can also be carried out smoothly. I saw that the npu of JP-BOX is also turned on. You can go Try to see if it can run the project you want to run. Because the dts do not completely match, some peripherals cannot be used. Currently, it is found that the tf card cannot be used.

谢谢提示,这样的话,目前我更偏向直接买块开发板或者jptv

**Comment by 13584452567** [comment]
主线内核没有rk的vpu支持，想用的话就只能用rk维护的5.10内核

**Comment by YouDianWeiLing** [comment]
> 主线内核没有rk的npu支持，想用的话就只能用rk维护的5.10内核

麻烦问下直接使用o大的库编译5.10内核，安装应用端的驱动就可以使用npu了吗

**Comment by LSP0123** [comment]
> > 主线内核没有rk的npu支持，想用的话就只能用rk维护的5.10内核
> 
> 麻烦问下直接使用o大的库编译5.10内核，安装应用端的驱动就可以使用npu了吗

#1319 

最新回复里

**Comment by YouDianWeiLing** [comment]
谢谢，我去看看

**Comment by YouDianWeiLing** [comment]
> > > 主线内核没有rk的npu支持，想用的话就只能用rk维护的5.10内核
> > 
> > 
> > 麻烦问下直接使用o大的库编译5.10内核，安装应用端的驱动就可以使用npu了吗
> 
> #1319
> 
> 最新回复里

谢谢，我去看看

**Comment by 13584452567** [comment]
我没太看懂，到底是要视频解码还是AI运算加速？解码是VPU处理的，NPU是用于加速AI运算的。这两个中的VPU，主线正在处理对于35系列的支持，NPU只能看看RK官方维护的5.10内核，想要移植到主线恐怕很难

**Comment by shirakun** [comment]
> 我没太看懂，到底是要视频解码还是AI运算加速？解码是VPU处理的，NPU是用于加速AI运算的。这两个中的VPU，主线正在处理对于35系列的支持，NPU只能看看RK官方维护的5.10内核，想要移植到主线恐怕很难

我需要NPU执行rknn的yolo,上面有其他人需要vpu

**Comment by 13584452567** [comment]
> > 我没太看懂，到底是要视频解码还是AI运算加速？解码是VPU处理的，NPU是用于加速AI运算的。这两个中的VPU，主线正在处理对于35系列的支持，NPU只能看看RK官方维护的5.10内核，想要移植到主线恐怕很难
> 
> 我需要NPU执行rknn的yolo,上面有其他人需要vpu
> 

https://github.com/unifreq/linux-6.1.y/issues/7

尝试一下5.10内核吧

**Comment by LSP0123** [comment]
> 我没太看懂，到底是要视频解码还是AI运算加速？解码是VPU处理的，NPU是用于加速AI运算的。这两个中的VPU，主线正在处理对于35系列的支持，NPU只能看看RK官方维护的5.10内核，想要移植到主线恐怕很难

可能是我理解错了，抱歉，因为之前在恩山看到个帖子说是rk356X系列解码是在npu
