### ISSUE TITLE
Could you improve the recognization of eth0 mac address correctly?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#213]
At current, after booting the armbian from eMMC or TF, the eth0 mac address is not recognized correctly. I've tried to test with X96 max (4+32, 2+16) and X96 air (2+16) and all the cases the mac address of ethernet is not correct.

Could you improve it in next version?

As before, I remember some Armbian version from Balbes could recognize the mac of ethernet correctly.
Thank you.

**Comment by ophub** [comment]
The MAC address of the device is obtained and allocated by U-BOOT during the startup process. U-BOOT will first get it from env. If it can't get it, then it will get it from efuse. If it can't get it again, it will call the function that randomly generates the MAC address. to generate automatically.

https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/sm.c

![Snip20220331_1](https://user-images.githubusercontent.com/68696949/160953803-7e9a1f93-c0c3-484b-8a0c-189681433862.png)
![22](https://user-images.githubusercontent.com/68696949/160953814-145dfda1-a0e4-49be-8c5d-d8e78c5fd901.jpg)
![33](https://user-images.githubusercontent.com/68696949/160953815-3e5e3fb9-192c-4370-8509-f7160588d9f8.jpg)


Since the TV box is an Android system, not the mainline kernel, the real MAC address of many devices in the mainline U-BOOT cannot be obtained in the actual measurement, and needs to be randomly assigned, which leads to random changes every restart.

Many users use SSH and remote desktop. The randomly changed MAC address and IP need to be searched in the router every time, which is very inconvenient. So we directly customize the MAC address, which can solve the above problems.

If you can accept random MAC and random IP, you can delete the MAC address in /etc/network/interface and let U-BOOT take over the processing.

I have no compulsion on whether to use the native MAC address, what I consider is to solve the problem that the device can be used normally. You can fork the source code and remove the fragment of the custom MAC address. I will keep this practice, I need to use it myself.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/43dada68cdcbf8eeba3f7fc6d97d8a8c2e4234e6/rebuild#L558-L560

**Comment by dinhchinh82** [comment]
thank you
