### ISSUE TITLE
it's possible to boot from USB/TF when the emmc slot is empty

### ISSUE THREAD

**Issue by cjz9032** [ophub/amlogic-s9xxx-armbian#2621]
I checked the guide, I found the first time to boot from USB require the device entering the android OS first to using adb command to reboot.
however, my device emmc slots is broken...so any ideas here

----
Device E900V22D
CPU S905L3A

thanks

**Comment by Abdalnablse10** [comment]
Like completely?
What's the name of your device?

**Comment by cjz9032** [comment]
> Like completely? What's the name of your device?

Device E900V22D
CPU S905L3A

**Comment by Abdalnablse10** [comment]
An amlogic, I have one called tx3 mini s905w so I think I can help.
I don't think you can start the device without the emmc.

If the emmc is totally broken like the chip itself is physically damaged then you're out of luck.

If it's a software brick you can reflash it using a A to A usb cable with the original firmware.

If the board refuses to enter flash mode because of the brick you can short a specific pin on the emmc.

There was no specific pin on the internet for my board so I had to find it by trail and error.

**Comment by cjz9032** [comment]
> An amlogic, I have one called tx3 mini s905w so I think I can help.
> I don't think you can start the device without the emmc.
> 
> If the emmc is totally broken like the chip itself is physically damaged then you're out of luck.
> 
> If it's a software brick you can reflash it using an A to A usb cable with the original firmware.
> 
> If the board refuses to enter flash mode because of the brick you can short a specific pin on the emmc.
> 
> There was no specific pin on the internet for my board so I had to find it by trail and error.

Got it. maybe the only way to fix that I need to weld the emmc slots as the slots only lost some joint I think it is not too hard to weld it，anyway thanks again

**Comment by Abdalnablse10** [comment]
You're welcome.
