### ISSUE TITLE
Upload kernel to release failed

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#307]
Hi @ophub , I try build kernel from kernel.org but when the kernel try upload to release there is a problem..
Thanks..

```
Run ncipollo/release-action@main
  with:
    tag: kernel_5.10.115_5.15.39_5.17.7
    artifacts: /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/compile-kernel/output/*
    allowUpdates: true
    body: The kernel can be used to compile Armbian and OpenWrt.
  
    generateReleaseNotes: false
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
  env:
    TZ: Asia/Shanghai
    COMPILE_STARTINGTIME: 05.13.1916
    PACKAGED_OUTPUTTAGS: 5.10.115_5.15.39_5.17.7
    PACKAGED_OUTPUTPATH: /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/compile-kernel/output
    PACKAGED_OUTPUTDATE: 2022.05.13.2243
    PACKAGED_STATUS: success
Error: Error undefined: Parameter token or opts.auth is required
```

**Comment by SajjadSabzkar** [comment]
Hi , 
Please Read the README file completely.
[use-github-actions-to-build](https://github.com/ophub/amlogic-s9xxx-armbian#use-github-actions-to-build)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#2-set-the-privacy-variable-github_token

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#3-fork-repository-and-set-gh_token

Since github.com has recently modified the settings of the fork repository, the read and write permissions of Workflow are disabled by default, so uploading to Releases requires adding `GITHUB_TOKEN` and `GH_TOKEN` to the repository and setting `Workflow read and write permissions`.
