### ISSUE TITLE
Overclock kernel

### ISSUE THREAD

**Issue by NewbieOrange** [ophub/amlogic-s9xxx-armbian#31]

**Comment by Jay-9527** [comment]
你好，那个您可否方便发布一下安装方法？

**Comment by Jay-9527** [comment]
Hello, can you release the installation method conveniently?

**Comment by Jay-9527** [comment]
Because I found it didn't work when I installed it, I wrote the image on the MAC system.

**Comment by pulpoff** [comment]
It would be very nice if 5.12.19 kernel sources were released, as it is the only kernel that runs at 2.2Ghz on GT King.
I am interested in porting the freq changes to 5.15 tree to make it run much faster.
Thanks.
![Screenshot from 2021-11-22 01-01-23](https://user-images.githubusercontent.com/40654959/142784407-f85fb38a-a0b7-4d91-ab70-95c84f78f578.png)

**Comment by pulpoff** [comment]
![Screenshot from 2021-11-22 01-01-56](https://user-images.githubusercontent.com/40654959/142784423-8bef6408-cd9a-42be-bbd9-92fe0d34c6da.png)

**Comment by pulpoff** [comment]
It seems there's a new tool and update here :+1: https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

I am trying to follow these steps to create a kernel now..

**Comment by ophub** [comment]
When `cross-compiling` the Armbian kernel in a system such as Ubuntu under the environment of `x86_64`, the `uInitrd` file cannot be generated. When the kernel file is packaged, the file of the same kernel series in the repository will be automatically used instead. At present, cross-compilation in the x86_64 environment cannot completely replace the kernel compilation in the real Armbian environment, and the produced kernel is unstable.

**Comment by pulpoff** [comment]
I found the freq table here :+1: 
root@mac:/usr/src/amlogic-s9xxx-armbian-main/compile-kernel/kernel/linux-5.15.4# pico arch/arm64/boot/dts/amlogic/meson-g12b-s922x.dtsi 

the missing freqs are added with patch from here
https://github.com/armbian/build/pull/2629/commits/d0831a7ce191759011d8a0f23019acebc2348149

**Comment by pulpoff** [comment]
file:///home/pulp/Documents/meson-g12b-s922x.dtsi

**Comment by ophub** [comment]
Try to adjust and compile.

**Comment by pulpoff** [comment]
Well, it worked
![Screenshot from 2021-11-22 03-06-32](https://user-images.githubusercontent.com/40654959/142790563-9b2b2761-8606-41fd-9620-bac3f4989e46.png)
![Screenshot from 2021-11-22 03-06-17](https://user-images.githubusercontent.com/40654959/142790566-42975cb9-ad7d-4f96-8ed6-b46db9f44851.png)
!

**Comment by pulpoff** [comment]
https://browser.geekbench.com/v5/cpu/111292
![Screenshot from 2021-11-22 03-16-33](https://user-images.githubusercontent.com/40654959/142791315-7ea1a2a9-3621-4cbe-b7ce-a46dd21bd3e9.png)
36

**Comment by ophub** [comment]
You can write a tutorial about your modification plan, and everyone can refer to it.

You can customize the signature of the compiled kernel. If you want to share it, you can publish it. I will put it in the kernel library for friends who need it.

**Comment by pulpoff** [comment]
i have uploaded the kernel here : [https://vp5.net/king/](url)

**Comment by pulpoff** [comment]
uname -a
Linux King 5.14.21-pulp #5 ZEN SMP PREEMPT Mon Nov 22 04:40:39 CET 2021 aarch64 aarch64 aarch64 GNU/Linux

I compiled latest ZEN kernel with Freq patches, you can get it from 
https://vp5.net/king/

**Comment by pulpoff** [comment]
I am using Dell 2.5K monitor with native res of 2560x1440,
it seems that these patches are also required to support it :+1: 
https://github.com/tobetter/linux/commit/248da29964751908c36e2c5558385ec09aed87ad

**Comment by pulpoff** [comment]
linux-5.14.21.tjz is my patched kernel src.
anybody can build it with required changed.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/2e7f8212831bdd6ec3b88bc4a538c185a11e7c65

Thanks for sharing, I have recorded to armbian pioneer list.

**Comment by pulpoff** [comment]
So, as we now have 2.2Ghz and its working properly..
Time to find out if this can be improved.
My kernel supports freq table from odroid n2+ (2.4Ghz)
But our dtb file only supports up to 2.2Ghz
To extract dts : 
`dtc -I dtb -o odroid.dts /boot/dtb/amlogic/meson-g12b-odroid-n2-plus.dtb`

I have extracted dts from gtking-oc.gtb, and here are freq settings:
A55:
`       opp-table-0 {
                compatible = "operating-points-v2";
                opp-shared;
                phandle = <0x4c>;

                opp-100000000 {
                        opp-hz = <0x00 0x5f5e100>;
                        opp-microvolt = <0xb2778>;
                };

                opp-250000000 {
                        opp-hz = <0x00 0xee6b280>;
                        opp-microvolt = <0xb2778>;
                };

                opp-500000000 {
                        opp-hz = <0x00 0x1dcd6500>;
                        opp-microvolt = <0xb2778>;
                };
.............
                opp-1992000000 {
                        opp-hz = <0x00 0x76bb8200>;
                        opp-microvolt = <0xf9448>;
                };
        };

`
and for A73 : 
`        opp-table-1 {
                compatible = "operating-points-v2";
                opp-shared;
                phandle = <0x4e>;

                opp-100000000 {
                        opp-hz = <0x00 0x5f5e100>;
                        opp-microvolt = <0xb7598>;
                };

                opp-250000000 {
                        opp-hz = <0x00 0xee6b280>;
                        opp-microvolt = <0xb7598>;
                };

                opp-500000000 {
                        opp-hz = <0x00 0x1dcd6500>;
                        opp-microvolt = <0xb7598>;
                };

                opp-667000000 {
                        opp-hz = <0x00 0x27c19cc0>;
                        opp-microvolt = <0xb7598>;
                };
.............
                opp-1992000000 {
                        opp-hz = <0x00 0x76bb8200>;
                        opp-microvolt = <0xf9448>;
                };
        };

`
Obviously we can change them according to previously posted kernel freqs.
The question is how to build dtb from modified dts file.
This is what i could find :+1: 
https://stackoverflow.com/questions/46469924/how-to-modify-kernel-dtb-file
Any help ?

**Comment by pulpoff** [comment]
------------------------------------------------------------------------
CONVERT dtb to dts
------------------------------------------------------------------------
dtc -I dtb -O dts /boot/dtb/allwinner/sun50i-a64-sopine-baseboard.dtb -o /boot/dtb/allwinner/sun50i-a64-sopine-baseboard.dts

------------------------------------------------------------------------
EDIT dts
------------------------------------------------------------------------
nano /boot/dtb/allwinner/sun50i-a64-sopine-baseboard.dts

------------------------------------------------------------------------
CONVERT (BACK) dts to dtb
------------------------------------------------------------------------			
dtc -I dts -O dtb /boot/dtb/allwinner/sun50i-a64-sopine-baseboard.dts -o /boot/dtb/allwinner/sun50i-a64-sopine-baseboard.dtb


reboot

**Comment by pulpoff** [comment]
So, i have rebuilt dtb file and it loads successfully
now i see this in dmesg :+1: 
[    1.117389] core: _opp_supported_by_regulators: OPP minuV: 1040000 maxuV: 1040000, not supported by regulator
[    1.124859] cpu cpu0: _opp_add: OPP not supported by regulators (2016000000)
[    1.131954] core: _opp_supported_by_regulators: OPP minuV: 1030000 maxuV: 1030000, not supported by regulator
[    1.141675] cpu cpu2: _opp_add: OPP not supported by regulators (2304000000)
[    1.148664] core: _opp_supported_by_regulators: OPP minuV: 1040000 maxuV: 1040000, not supported by regulator
[    1.158492] cpu cpu2: _opp_add: OPP not supported by regulators (2400000000)

**Comment by pulpoff** [comment]
I uploaded my modified dts and dtb file as gtking-current

**Comment by pulpoff** [comment]
I also uploaded the kernel : -GT

**Comment by pulpoff** [comment]
I found these new values from odroid n2+ dtb :+1: 

        regulator-vddcpu-a {
                compatible = "pwm-regulator";
                regulator-name = "VDDCPU_A";
                regulator-min-microvolt = <0xa6040>;
                regulator-max-microvolt = <0xfde80>;
                pwm-supply = <0x49>;
                pwms = <0x4b 0x00 0x5dc 0x00>;
                pwm-dutycycle-range = <0x64 0x00>;
                regulator-boot-on;
                regulator-always-on;
                phandle = <0x46>;
        };

        regulator-vddcpu-b {
                compatible = "pwm-regulator";
                regulator-name = "VDDCPU_B";
                regulator-min-microvolt = <0xa6040>;
                regulator-max-microvolt = <0xfde80>;
                pwm-supply = <0x49>;
                pwms = <0x4c 0x01 0x5dc 0x00>;
                pwm-dutycycle-range = <0x64 0x00>;
                regulator-boot-on;
                regulator-always-on;
                phandle = <0x44>;
        };
0xfde80 equals 1040000 :)

**Comment by pulpoff** [comment]
We are getting somewhere!!

pulp@King:~$ uname -a
Linux King 5.15.5-low #9 SMP PREEMPT Fri Nov 26 01:05:00 CET 2021 aarch64 aarch64 aarch64 GNU/Linux
pulp@King:~$ htop
pulp@King:~$ freq
100000 250000 500000 667000 1000000 1200000 1398000 1512000 1608000 1704000 1800000 1908000 2016000 
100000 250000 500000 667000 1000000 1200000 1398000 1512000 1608000 1704000 1800000 1908000 2016000 2100000 2208000 2304000 2400000 
pulp@King:~$

**Comment by pulpoff** [comment]
![Screenshot from 2021-11-26 01-21-46](https://user-images.githubusercontent.com/40654959/143509946-cd687a78-1bd8-4956-8ae1-c52afcd7ab0f.png)
![Screenshot from 2021-11-26 01-21-26](https://user-images.githubusercontent.com/40654959/143509964-e0fb844a-df71-4f34-91b8-929c60064668.png)
![Screenshot from 2021-11-26 01-21-11](https://user-images.githubusercontent.com/40654959/143509968-08f72114-58e5-4cd1-8ad7-2c2c87e1d9c8.png)

**Comment by pulpoff** [comment]
kernel : 5.15.5-low
dtb.img

both files uploaded.

**Comment by pulpoff** [comment]
https://browser.geekbench.com/v5/cpu/112158
![Screenshot from 2021-11-26 01-34-48](https://user-images.githubusercontent.com/40654959/143510608-ce2fb88b-99b3-4115-b008-43115361e131.png)
96

**Comment by pulpoff** [comment]
sbc-bench v0.8.4

Installing needed tools. This may take some time. Done.
Checking cpufreq OPP. Done.
Executing tinymembench. This will take a long time. Done.
Executing OpenSSL benchmark. This will take 3 minutes. Done.
Executing 7-zip benchmark. This will take a long time. Done.
Checking cpufreq OPP... Done.

Memory performance (big.LITTLE cores measured individually):
memcpy: 2008.2 MB/s (0.3%)
memset: 7670.3 MB/s 
memcpy: 3721.4 MB/s 
memset: 6805.4 MB/s 

7-zip total scores (3 consecutive runs): 9641,9629,9617

OpenSSL results (big.LITTLE cores measured individually):
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     175612.00k   522553.51k  1010934.10k  1356122.45k  1505957.21k  1514848.26k
aes-128-cbc     421197.46k  1041959.30k  1583586.30k  1808756.74k  1902242.47k  1908894.38k
aes-192-cbc     167370.47k   458932.10k   825348.44k  1045608.11k  1133819.22k  1139343.36k
aes-192-cbc     391137.00k   926246.25k  1322970.88k  1519525.55k  1586981.55k  1591716.52k
aes-256-cbc     162310.23k   427726.51k   715113.98k   874855.77k   935717.55k   938906.97k
aes-256-cbc     377643.53k   846759.10k  1185863.00k  1311776.43k  1361529.51k  1364961.96k

Full results uploaded to http://ix.io/3G88. Please check the log for anomalies (e.g. swapping
or throttling happenend) and otherwise share this URL.

In case this device is not already represented in official sbc-bench results list then please
consider submitting it at https://github.com/ThomasKaiser/sbc-bench/issues with this line:
| Beelink GT-King Pro | 2400/2016 MHz | 5.15 | Impish arm64 | 9630 | 298400 | 1151930 | 2013720 | 7676810 | - | [http://ix.io/3G88](http://ix.io/3G88) |

**Comment by pulpoff** [comment]
kernel src is uploaded : 
linux-5.15.5-low.src.zip

**Comment by pulpoff** [comment]
Ok funny enough, i could overclock further .
![Screenshot from 2021-11-30 03-02-49](https://user-images.githubusercontent.com/40654959/143972650-dd8c70c1-616b-4a8e-94b4-a259f7eec650.png)
.

**Comment by pulpoff** [comment]
![Screenshot from 2021-11-30 06-18-26](https://user-images.githubusercontent.com/40654959/143990203-514184a2-11ed-44ec-baac-9a58b26dfdb8.png)
![Screenshot from 2021-11-30 06-18-03](https://user-images.githubusercontent.com/40654959/143990205-14d618d9-24e4-41e4-b37d-d7cae8be3c25.png)

**Comment by pulpoff** [comment]
https://browser.geekbench.com/v5/cpu/1132830
![Screenshot from 2021-11-30 06-26-56](https://user-images.githubusercontent.com/40654959/143990623-01386181-ac88-4a1d-ae48-911a1e23b053.png)
4

**Comment by pulpoff** [comment]
The thermal protection is working well, freq changed back quickly if overheat 
![Screenshot from 2021-11-30 07-07-14](https://user-images.githubusercontent.com/40654959/143994626-3766e9b6-581d-4db3-9fa1-e62f59393378.png)
:

**Comment by pulpoff** [comment]
https://browser.geekbench.com/v5/cpu/113293
![Screenshot from 2021-11-30 07-58-58](https://user-images.githubusercontent.com/40654959/144000511-b0ff25e8-f5a2-4703-ba5b-e2eaeccedb70.png)
87

**Comment by pulpoff** [comment]
arch/arm64/boot/dts/amlogic/meson-g12b-s922x.dtsi file is uploaded to vp5.net/king/

**Comment by pulpoff** [comment]
![Screenshot from 2021-12-18 01-30-24](https://user-images.githubusercontent.com/40654959/146622349-de1741fc-0b84-4de3-9c3c-df0e997d052e.png)

**Comment by pulpoff** [comment]
https://browser.geekbench.com/v5/cpu/1166769
![Screenshot from 2021-12-18 02-41-52](https://user-images.githubusercontent.com/40654959/146624875-172c5ef4-4d0c-4f9f-b999-8f96adc88781.png)
2

**Comment by pulpoff** [comment]
![Screenshot from 2021-12-18 02-43-34](https://user-images.githubusercontent.com/40654959/146624930-a48c976c-df50-4520-baf0-e6b95083bc79.png)

**Comment by pulpoff** [comment]
5.15.10-pulp.zip

**Comment by MX10-AC2N** [comment]
@pulpoff 
I own a Beelink GtKing-Pro and wanted to know which u-boot.ext you used to boot your 5.15.y system on SD card ?

**Comment by pulpoff** [comment]
> @pulpoff I own a Beelink GtKing-Pro and wanted to know which u-boot.ext you used to boot your 5.15.y system on SD card ?

i have used original armbian in this thread and installed on emmc, whatever u-boot this installs by default ..

**Comment by pulpoff** [comment]
sbc-bench v0.8.4

Installing needed tools. This may take some time. Done.
Checking cpufreq OPP...ls: cannot access '/sys/devices/system/cpu/cpufreq/policy?/stats/time_in_state': No such file or directory
 Done.
Executing tinymembench. This will take a long time. Done.
Executing OpenSSL benchmark. This will take 3 minutes. Done.
Executing 7-zip benchmark. This will take a long time...ls: cannot access '/sys/devices/system/cpu/cpufreq/policy?/stats/time_in_state': No such file or directory
 Done.
Checking cpufreq OPP... Done.

ls: cannot access '/sys/devices/system/cpu/cpufreq/policy?/stats/time_in_state': No such file or directory
Memory performance (big.LITTLE cores measured individually):
memcpy: 1947.6 MB/s 
memset: 7927.2 MB/s 
memcpy: 3675.8 MB/s 
memset: 7109.9 MB/s 

7-zip total scores (3 consecutive runs): 9840,9885,9913

OpenSSL results (big.LITTLE cores measured individually):
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     191693.25k   570383.38k  1103535.87k  1480247.30k  1640966.83k  1651976.87k
aes-128-cbc     459681.83k  1137583.21k  1728555.01k  1973924.52k  2076185.94k  2081805.65k
aes-192-cbc     182706.59k   502783.77k   900973.91k  1141420.37k  1236088.15k  1241655.98k
aes-192-cbc     426857.82k  1010069.14k  1441687.72k  1658283.69k  1731974.49k  1737321.13k
aes-256-cbc     177151.89k   465943.25k   780609.88k   954859.18k  1019781.12k  1023584.94k
aes-256-cbc     412141.13k   923912.00k  1294000.04k  1431674.88k  1485960.53k  1489851.73k

Full results uploaded to http://ix.io/3JaS. Please check the log for anomalies (e.g. swapping
or throttling happenend) and otherwise share this URL.
