### ISSUE TITLE
X96 Max Plus 100W  Ethernet/Wifi problem

### ISSUE THREAD

**Issue by jbyu** [ophub/amlogic-s9xxx-armbian#566]
Hi,  I got a tv box, X96 Max Plus_100W 4GRam, LAN 100m, 2 antennas, radio module W522A.
Booted by Armbian_22.11.0_Aml_s905x3_bullseye_5.15.62_server_2022.09.09 with meson-sm1-x96-max-plus-100m.dtb.
But Ethernet/Wifi are not working.
 
I had tried 
meson-sm1-x96-max-plus.dtb
meson-sm1-x96-max-plus-q2.dtb
meson-sm1-sei610.dtb

None of them works.

![IMG_20220510_130759_](https://user-images.githubusercontent.com/978990/190605533-2546af6a-1d4a-4c53-8c02-bf8795b414b9.jpg)

**Comment by ophub** [comment]
meson-sm1-x96-air.dtb

**Comment by jbyu** [comment]
Doesn't work with meson-sm1-x96-air.dtb, either.

Failed to start Raise network interface.
Failed to start Access point and authentication server for Wi-Fi and Ethernet.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md

**Comment by trvqhuy** [comment]
@ophub I'm current having the same experience with @jbyu for my X96 Max Plus 100W.

**Device specifications:**
- Name: X96 Max Plus 100W
- CPU: Amlogic S905X3 quad-core ARM Cortex A55
- GPU: ARM Mali-G31MP
- Radio module: W522A
- Memory: DDR3 4GB, FLASH 32GB
- Support 10/100M Ethernet, 2.4 and 5G WiFi, BT4.0;
- USB3.0 x 1, USB2.0 x 1, TF Card
- HDMI, AV, SPDIF

**Software informations:**
- Armbian image: Armbian_22.11.0_Aml_s905x3_jammy_5.15.62_server_2022.09.13.img

**Descriptions**
At first, I used the 'meson-sm1-x96-air.dtb' file for the OS Installation as the [Instructions](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md) mentioned, but the system shows only 2GB instead of 4GB, and also the Wifi connection is unavailable. 

I've tried extracting the DTB file from the TV Box's Original Firmware (Android 9), with 4 raw DTS files shown in the [drive](https://drive.google.com/drive/folders/19ZoOEo5c5Ca7U48NtAfFLx2ErqLUA2JB?usp=sharing). After a few trials of modifying the 'meson-sm1-x96-air.dtb' file (already converted to DTS) based on the original DTS file 'sm1-ac213-4g.dts' from the drive link above, I've successfully got the whole 4GB displayed on the Armbian OS as the picture below.

Unfortunately, after lots of trying on modifying **Wifi** and **PCIE** related fields from the DTB file, the Wifi driver is still not available.

![image](https://user-images.githubusercontent.com/88963333/190618832-98f75b99-f11e-42b2-9a3b-0f6a80c510ec.png)

Could you please show us any way to fix this problem?

Thank you in advance.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-air.dts


This is the source code

**Comment by trvqhuy** [comment]
So is it means that I needed to add the `bluetooth` field with `&uart_A` for my own case in order to make the Wifi driver works properly?

**Comment by ophub** [comment]
Confirm your chip, you can find similar code from other files in the kernel library, refer to add, compile and test

**Comment by trvqhuy** [comment]
I've tried looking for the similar code for the `W522A` Wifi+BT chip.

Unfortunately there was zero results after lots of researching, that's why I have to find another way - extracting the DTS files from the TV Box in order to achieve this. But I just found this only, and directly import these field into the armbian DTS file made no difference:
```
        wifi {
		compatible = "amlogic, aml_wifi";
		dev_name = "aml_wifi";
		status = "okay";
		interrupt_pin = <0x19 0x49 0x00>;
		irq_trigger_type = "GPIO_IRQ_LOW";
		power_on_pin = <0x19 0x48 0x00>;
		dhd_static_buf;
		pinctrl-names = "default";
		pinctrl-0 = <0x6d>;
		pwm_config = <0x6e>;
	};

	wifi_pwm_conf {
		phandle = <0x6e>;

		pwm_channel1_conf {
			pwms = <0x6b 0x00 0x774d 0x00>;
			duty-cycle = <0x3ba6>;
			times = <0x0a>;
		};

		pwm_channel2_conf {
			pwms = <0x6b 0x02 0x7724 0x00>;
			duty-cycle = <0x3b92>;
			times = <0x0c>;
		};
	};
```
Could you please instruct me how to port this into the armbian dts file?

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12b-gtking-pro-rev_a.dts

You copied the Android code, which cannot be added to the source code of the mainline kernel.

The code of wifi and bluetooth in the mainline kernel can be seen in the standard writing in this file.

**Comment by ophub** [comment]
Is the img firmware you posted in the google network disk the Android firmware of your box?

Can you identify the location of the shorting contacts on this board?

**Comment by trvqhuy** [comment]
@ophub yes, it is the manufacture firmware of the `X96 Max Plus 100W` box.

Sorry I've missed your point on "location of the shorting contacts".
I don't really interfere with the box's hardware, I've only used the "toothpick" method.

**Comment by ophub** [comment]
https://fcc.report/FCC-ID/ZQ6-W522A
I didn't find his driver source code in the mainline kernel

**Comment by ophub** [comment]
https://user-images.githubusercontent.com/68696949/110590933-67785300-81b3-11eb-9860-986ef35dca7d.jpg

**Comment by trvqhuy** [comment]
Okay I get it, so could your please tell us what to do next?

**Comment by trvqhuy** [comment]
It's a pity that this W522A module is such a new chip, so that there's no support available on the Internet.

**Comment by ophub** [comment]
These boxes are produced for watching TV, so Android will support it at the earliest, and then the manufacturer will submit the driver to the mainline kernel and try again.

**Comment by trvqhuy** [comment]
So basically the issue seems really tricky to be fixed unless the manufacturer release his driver to the mainline kernel.
Am I right?

**Comment by ophub** [comment]
Some people will share their open source drivers

**Comment by Travis90x** [comment]
Same lack of drivers for the recent X96 Max+ 2101 and 2101W (LAN 1Gb JL2101) W522A radio module (Fn-Link K255B-SR).
Photo: https://4pda.to/forum/index.php?showtopic=1013103&st=9840#Spoil-117458872-1

Other hardware variant are detailed here
https://4pda.to/forum/index.php?showtopic=1013103&st=40#entry102780026

Other useful link:
https://manuals.plus/ampak/w522a-evaluation-board-manual#fcc_caution
https://electric.garden/ampak-zq6/1tx-1rx-802-11-ac-a-b-g-n-wi-fi-bt-5-0-mod-w522a

**Comment by luucasmooreira** [comment]
As of today, no solution?

**Comment by trvqhuy** [comment]
Hi @luucasmooreira, have you tried the solution mentioned by user @tv4you2016?

> @D-Sta follow the following steps:
> 
> 1. install original android firmware
> 2. prepare the pen/sdcard with the Armbian_23.02.0_amlogic_s905x3_jammy_5.15.82_server_2022.12.08.img.gz
> 3. download the https://github.com/ophub/amlogic-s9xxx-armbian/files/10200168/meson-sm1-x96-max-plus-q1.dtb.zip
>    put file in /dtb/amlogic/
> 4. In uEnv.txt modified the DTB like that FDT=/dtb/amlogic/meson-sm1-x96-max-plus-q1.dtb
> 5. [run the usb  go to **/etc/model_database.conf**
>    Modify one line, such as the line corresponding to 516
>    ](https://github.com/ophub/amlogic-s9xxx-armbian/issues/788#issuecomment-1345274610)

**Comment by trvqhuy** [comment]
I'm having the same wifi problem with W522A radio module and would love to hear your feedback for that solution.

**Comment by Techie-Anand** [comment]
> Doesn't work with meson-sm1-x96-air.dtb, either.
> 
> Failed to start Raise network interface. Failed to start Access point and authentication server for Wi-Fi and Ethernet.

can you have DTB file because i also face ethernet network issue all things are ok but ethernet is not working

**Comment by Techie-Anand** [comment]
> Doesn't work with meson-sm1-x96-air.dtb, either.
> 
> Failed to start Raise network interface. Failed to start Access point and authentication server for Wi-Fi and Ethernet.

Can you provide me the working DTB files for ethernet

**Comment by Techie-Anand** [comment]
> meson-sm1-x96-air.dtb

Tried this DTB but did not worked for me

**Comment by ophub** [comment]
You try using the 5.15 kernel

**Comment by Techie-Anand** [comment]
> You try using the 5.15 kernel

yes i am using that kernel 5.15 but ethernet is not worked

**Comment by Orefie** [comment]
I have the same radio module on my x96 max plus 2101W board .
I found some information.
the W552a is a Fn-Link K255B-SR
The Fn-Link K255B-SR is an Amlogiq W155S1 chip.
see the datasheet
https://usermanual.wiki/HUNAN-FN-LINK-TECHNOLOGY/K255B-SR.User-Manual-5353157.pdf
I found two github for the sources of this module.
https://github.com/CoreELEC/w1-aml
https://github.com/adeepn/w1-aml
if it can help you, thanks for your work ;)

**Comment by nickolay** [comment]
> https://github.com/adeepn/w1-aml

This seems to be the driver [used](https://github.com/armbian/build/commit/d65b245be62410a6b35d63d11c9e9516b12f188a#diff-dd3456456bdbe6cb4602ef040892600f4bebca8fb5d02ee42adc8013ceca98fcR608) to support the W155S1 chipset in Jethome's [Jethub D1+](https://docs.jethome.ru/en/controllers/linux/din_rail/d1p.html). They use it to provide [their own builds](https://fw.jethome.ru/devices/jethome/D1P/) of armbian, as this particular bit does not seem to be upstreamed (yet?).

**Comment by laigor** [comment]
https://github.com/khadas/wifi-amlogic-w1
