### ISSUE TITLE
X96MaxPlus touched by CoreELEC cannot boot armbian

### ISSUE THREAD

**Issue by chen-xin** [ophub/amlogic-s9xxx-armbian#74]
I have a X96MaxPlus(4G/32g, 1gbit nic), which once boot into CoreELEC  9.2.8 on usb stick, now it cannot boot armbian: 

If I press reset while power on, or do `adb reboot update`, it leads to the droid down "no command" screen, otherwise it boot into Android.

I tried the instructions from  [CoreELEC启动后无法再启动Armbian？看这里！](https://post.smzdm.com/p/ad2vo52k/) but not working.

I am able to boot into CoreELEC without pressing reset or `adb reboot update`, which is not like the above article.

How can I resolve this? Any clue would be appreciated, thank you.

**Comment by ophub** [comment]
Generally, `restore to the original Android TV system first`, and then install it.

However, there is a version of X96 Max+ that cannot be used in `V5.1`. The network card chip `IP1001M` can be used in Android, but the mainline kernel has not been driven yet.

**Comment by chen-xin** [comment]
Thank you! I will try the  advice and inform you the result.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by test012012** [comment]
> Generally, `restore to the original Android TV system first`, and then install it.
> 
> However, there is a version of X96 Max+ that cannot be used in `V5.1`. The network card chip `IP1001M` can be used in Android, but the mainline kernel has not been driven yet.

BTW, when I googled for my issue, I found that Coreelec team fixed the issue with IP1001M. https://discourse.coreelec.org/t/x96-max-revision-ai-icplus-ip1001-lan-is-not-working/16885/74

Maybe it is possible to cherry-pick their fix to ophub images

**Comment by ophub** [comment]
This is good news, I have sent the driver link to flippy to see if I can put it directly into his kernrl source library

**Comment by test012012** [comment]
> This is good news, I have sent the driver link to flippy to see if I can put it directly into his kernrl source library

As I understood, it's a driver+dtb fix, not sure. The best way to understand is to check coreelec commits

**Comment by ophub** [comment]
ok

**Comment by FauthD** [comment]
Hi,
you can fix the issue with Armbian/LE boot after running CE easily.
Boot to u-boot shell and delete the environment variable "bootfromsd".
`setenv bootfromsd`
`saveenv`
The reason is that the aml_autoscript from Armbian/LE does this check in first place:
`if printenv bootfromsd; then exit;`
So if that variable exists, it does not touch the boot details.

IMHO that is easier and faster than reflashing the complete image. In my case I had not even the original image available (Tanix TX3). Therefore I had to analyze the boot process.

Many ragards, Dieter

**Comment by FauthD** [comment]
Hi chen-xin,
see my findings and details on [my github](https://github.com/FauthD/amlogic-u-boot-scripts).
There is a chapter about fixing the CoreElec issue. Actually it is more an issue with the bootscript of Armbian. I called the headline "Sabotage".

Many ragards, Dieter

PS: I looked into CE because I have trouble booting into kernel V4.9.x on the Tanix TX3.
Runs fine with CE and the DT sm1_s905x3_4g_1gbit.dtb. There is also a flavour with the "1gbit". That could fit to the X96max+.
With Kernel 5.16.10 I can boot fine with the DT for the X96max+. So the TX3 is similar to your box.

My TX3 was advertised with 100Mbit, but it runs fine with 1gbit on Linux.

**Comment by frong73** [comment]
hello,
i was on coreelec and couldn't boot to uboot-shell or access serial port to set the bootfromsd enviornment variable. Needed days to figure out you can ssh to your box and use fw_setenv to set the variable. 
Hope I can save somebody's time with my first post here :-)
