### ISSUE TITLE
Kernel doesn't have dvb drivers

### ISSUE THREAD

**Issue by sinancetinkaya** [ophub/amlogic-s9xxx-armbian#890]
Many Mecool devices have AVL6862 tuner but the kernel doesn't have a driver for it. 
You can find driver source code here https://github.com/afl1/dvb_tv-aml

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/341

Don't repeat the question, search the previous question first.

**Comment by sinancetinkaya** [comment]
That has nothing to do with AVL6862.
Nevermind, I just wondered why you marked this as "completed" since it hasn't.

**Comment by ophub** [comment]
Ask the customer service of github why the closed question will be displayed as completed, and let them modify it.

I will close the issue for more than 3 days, no matter how much this issue is discussed. The discussion for too long can continue after closing, but I don't want to provide more energy for a problem.
